#!/usr/bin/env bash

CUR_DIR=$(dirname "$0")

cp $CUR_DIR/.gdbinit_peda $CUR_DIR/gdbinit # use peda as gdb

cmd="gdb"

# check if we need the sudo command
for var in "$@"
do
    if [ $var = "-p" ]; then
        cmd="sudo $cmd"       
    fi
done

$cmd "$@" # execute gdb with the given arguments
